apiVersion: v1
entries:
  antrea:
  - apiVersion: v2
    appVersion: 1.8.0-alpha.2
    created: "2022-07-08T21:00:35.575249824Z"
    description: Kubernetes networking based on Open vSwitch
    digest: 126e4b13e38572d780224566c6b8b394192d1226cff4ae38b231350c1e99e578
    home: https://antrea.io/
    icon: https://raw.githubusercontent.com/antrea-io/antrea/main/docs/assets/logo/antrea_logo.svg
    keywords:
    - Kubernetes
    - CNCF
    - Networking
    - CNI
    - Security
    - Open vSwitch
    - OVS
    kubeVersion: '>= 1.16.0-0'
    name: antrea
    sources:
    - https://github.com/antrea-io/antrea
    type: application
    urls:
    - https://github.com/antrea-io/antrea/releases/download/v1.8.0-alpha.2/antrea-chart.tgz
    version: 1.8.0-alpha.2
  - apiVersion: v2
    appVersion: 1.8.0-alpha.1
    created: "2022-07-07T16:26:58.826240801Z"
    description: Kubernetes networking based on Open vSwitch
    digest: 851eb35c50464aa4de2e5dfa71116b2194e17c09f66a5761c749635908767410
    home: https://antrea.io/
    icon: https://raw.githubusercontent.com/antrea-io/antrea/main/docs/assets/logo/antrea_logo.svg
    keywords:
    - Kubernetes
    - CNCF
    - Networking
    - CNI
    - Security
    - Open vSwitch
    - OVS
    kubeVersion: '>= 1.16.0-0'
    name: antrea
    sources:
    - https://github.com/antrea-io/antrea
    type: application
    urls:
    - https://github.com/antrea-io/antrea/releases/download/v1.8.0-alpha.1/antrea-chart.tgz
    version: 1.8.0-alpha.1
  flow-aggregator:
  - apiVersion: v2
    appVersion: 1.8.0-alpha.2
    created: "2022-07-08T19:08:08.000163264Z"
    description: Antrea Flow Aggregator
    digest: 604a090a12245ff8f3d77338a5b6f5cf935bb9b302d70aa75cae26bbb3bdda58
    home: https://antrea.io/
    icon: https://raw.githubusercontent.com/antrea-io/antrea/main/docs/assets/logo/antrea_logo.svg
    keywords:
    - Kubernetes
    - CNCF
    - Networking
    - CNI
    - Security
    - Open vSwitch
    - OVS
    - Antrea
    - Observability
    - Flow Visibility
    - Flow Aggregator
    kubeVersion: '>= 1.16.0-0'
    name: flow-aggregator
    sources:
    - https://github.com/antrea-io/antrea
    type: application
    urls:
    - https://github.com/antrea-io/antrea/releases/download/v1.8.0-alpha.2/flow-aggregator-chart.tgz
    version: 1.8.0-alpha.2
  theia:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "false"
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.2.0
    created: "2022-08-18T07:41:03.617087532Z"
    description: Antrea Network Flow Visibility
    digest: 165098ceb35900b51aa6f77450ac9b4eb0b125c97e4d25368a02485ff9e0b675
    home: https://antrea.io/
    icon: https://raw.githubusercontent.com/antrea-io/antrea/main/docs/assets/logo/antrea_logo.svg
    keywords:
    - Kubernetes
    - CNCF
    - Networking
    - CNI
    - Security
    - Open vSwitch
    - OVS
    - Antrea
    - Observability
    - Flow visibility
    kubeVersion: '>= 1.16.0-0'
    name: theia
    sources:
    - https://github.com/antrea-io/theia
    type: application
    urls:
    - https://github.com/antrea-io/theia/releases/download/v0.2.0/theia-chart.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.2.0-alpha.0
    created: "2022-07-08T19:00:11.16437322Z"
    description: Antrea Network Flow Visibility
    digest: f1045abd25cb4495a7950b47a5f385b5d37f6d83b31f549d795450d7126ad2cd
    home: https://antrea.io/
    icon: https://raw.githubusercontent.com/antrea-io/antrea/main/docs/assets/logo/antrea_logo.svg
    keywords:
    - Kubernetes
    - CNCF
    - Networking
    - CNI
    - Security
    - Open vSwitch
    - OVS
    - Antrea
    - Observability
    - Flow visibility
    kubeVersion: '>= 1.16.0-0'
    name: theia
    sources:
    - https://github.com/antrea-io/theia
    type: application
    urls:
    - https://github.com/antrea-io/theia/releases/download/v0.2.0-alpha.0/theia-chart.tgz
    version: 0.2.0-alpha.0
generated: "2022-08-18T07:41:03.612570114Z"
